backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: master
  ### enable below lines for github integration ###
  # name: github
  # repo: surjithctly/neat-starter
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "src/_data/homepage.yaml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Hero Banner Title, name: heroBannerTitle, widget: string }
          - { label: Hero Banner Sub Title, name: heroBannerSubtitle, widget: string }
    editor:
      preview: false